"""Your migration message

Revision ID: 74acc788cd3e
Revises: fadefedfd0a4
Create Date: 2023-11-20 10:17:25.208901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74acc788cd3e'
down_revision = 'fadefedfd0a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('date_imported', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('longitude', sa.String(length=20), nullable=False))
        batch_op.drop_column('version_num')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_num', sa.VARCHAR(length=32), nullable=False))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('date_imported')
        batch_op.drop_column('image')

    # ### end Alembic commands ###
