"""empty message

Revision ID: fadefedfd0a4
Revises: 
Create Date: 2023-11-13 21:30:38.327791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fadefedfd0a4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('class_type', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('image_data', sa.Column('id', sa.Integer, primary_key=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image_data', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('class_type')

    # ### end Alembic commands ###
